### ISSUE TITLE
About optimize Pctxt

### ISSUE THREAD

**Issue by shouwangzhe200** [open-mmlab/PowerPaint#10]
![image](https://github.com/zhuang2002/PowerPaint/assets/143770251/d7f5bce0-ec89-4121-8d44-b4af5bb2b7e7)
According to above equation, is it only the learnable prompt Pctxt trained during finetune? Or the paramters of Unet are also finetuned at the same time?

**Comment by icsl-Jeon** [comment]
I am also very curious..

**Comment by lijiaxing0213** [comment]
Optimization should only be performed on the embeddings of the task prompt, while the parameters of the unet are frozen. You can refer to the implementation of the EmbeddingLayerWithFixes class at https://mmagic.readthedocs.io/en/latest/autoapi/mmagic/models/editors/disco_diffusion/clip_wrapper/index.html#mmagic.models.editors.disco_diffusion.clip_wrapper.EmbeddingLayerWithFixes.

**Comment by Tord-Zhang** [comment]
> Optimization should only be performed on the embeddings of the task prompt, while the parameters of the unet are frozen. You can refer to the implementation of the EmbeddingLayerWithFixes class at https://mmagic.readthedocs.io/en/latest/autoapi/mmagic/models/editors/disco_diffusion/clip_wrapper/index.html#mmagic.models.editors.disco_diffusion.clip_wrapper.EmbeddingLayerWithFixes.

@lijiaxing0213 I am a little comfused. Since only the embeddings of task prompts are optimized and other parameters are frozen, if we use SD-inpaint as the base model, does that means no params in the UNET or text_encoder is updated? Then why release two different version in huggingface?

**Comment by zengyh1900** [comment]
Hi @Tord-Zhang, @icsl-Jeon @lijiaxing0213 @shouwangzhe200 
I appreciate your patience. Since there are two versions supported in this repo, it can be not very clear. 
We clarify that,
1. `powerpaint-v1` is based on unet model architecture, both the embeddings for task prompt and the whole unet are trainable.
2. `powerpaint-v2` is based on brushnet model architecture, that means only the embeddings for task prompt and the brushnet are trainable, while the unet is frozen. 

We have released our training configurations and scripts for [ppt-v1](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt1_sd15.py#L755) and [pp2-v2](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt2_bn.py#L698) for your reference.
