### ISSUE TITLE
Details preserve (Blend mode?)

### ISSUE THREAD

**Issue by dx777** [open-mmlab/PowerPaint#46]
Is there a possibility to preserve details during inpainting? Like the text for example. 
Brushnet has a "blended" flag, which I believe they use to just paste the input image on top of the result image, which in the case of powerpaint does not look good, since the shape is a bit mismatched.

**Comment by zengyh1900** [comment]
Hi @dx777, 

Thanks for your attention. 
1. Yes. PowerPaint can also paste the generated region back to the original image. However, a problem may raise that the generated content may show some color shift compared with the original image. We will try to solve it. 
2. As for the issue of 'mismatched shape', would you mind showing some results ?

**Comment by zengyh1900** [comment]
Hi @lanson07 

Thank you for your patience. Regarding the color shift problem, we suspect there are several reasons:
1. Details are lost due to the VAE (Variational Autoencoder) encoding and decoding process.
2. Images with high contrast (e.g., extremely black or white) are prone to color shift issues due to the limitations of the base model in synthesizing such high-contrast images.

While it may be somewhat beyond our scope to address these two issues, we welcome all possible solutions and discussions.

**Comment by zhLawliet** [comment]
@zengyh1900 你好，如上文所示，感觉不仅仅丢失细节了，整个图像的光照发生了明显的变化，也就是生成的图像明显比原图变的灰暗了，这个是已知问题吗？还是哪里不对。

![image](https://github.com/user-attachments/assets/04c168b2-244b-46c3-92be-94fa2cd7ec98)
![image](https://github.com/user-attachments/assets/2d35e08f-228b-4be9-95a6-69d1d571bb12)
